### ISSUE TITLE
lateinit property chunks has not been initialized

### ISSUE THREAD

**Issue by DamonChen117** [deepmedia/Transcoder#143]
Currently this issue is only found in MI devices.

Version:0.10.3
Android 9
Device: MI 8 Lite

Exception:
```
kotlin.UninitializedPropertyAccessException: lateinit property chunks has not been initialized 
 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueueEos(AudioEngine.kt:54) 
 	at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueueEos(AudioEngine.kt:21) 
 	at com.otaliastudios.transcoder.internal.pipeline.QueuedStep.step(steps.kt:39) 
 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51) 
 	at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28) 
 	at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18) 
 	at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114) 
 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:50) 
 	at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2) 
 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102) 
 	at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99) 
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
 	at java.lang.Thread.run(Thread.java:919) 
 
```

**Comment by bharatbiswal** [comment]
I observed this on my OnePlus device too running Android 10

**Comment by natario1** [comment]
Can you post the media file + instructions to reproduce?

**Comment by yuyuan20** [comment]
Yes. I experienced the exact issue in my Redmi 8A, using the latest transcoder version.

**Comment by DamonChen117** [comment]
> Can you post the media file + instructions to reproduce?

Sorry, this issue was reported from user. I don't have the media files.

**Comment by Aracoix** [comment]
same
