### ISSUE TITLE
Attempt to invoke virtual method 'void com.otaliastudios.transcoder.transcode.internal.AudioEngine.drainDecoder(int, java.nio.ByteBuffer, long, boolean)' on a null object reference

### ISSUE THREAD

**Issue by siegie2000** [deepmedia/Transcoder#155]
E/Transcoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.otaliastudios.transcoder.transcode.internal.AudioEngine.drainDecoder(int, java.nio.ByteBuffer, long, boolean)' on a null object reference
        at com.otaliastudios.transcoder.transcode.AudioTrackTranscoder.onDrainDecoder(AudioTrackTranscoder.java:70)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainDecoder(BaseTrackTranscoder.java:250)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:165)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:373)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

I can't follow the stacktrace above, because the codebase was changed. Possibly the issue was fixed. Please let me know if you have any comments.
