### ISSUE TITLE
java.lang.IllegalStateException: Of all AUDIO sources, some have a AUDIO track, some don't.

### ISSUE THREAD

**Issue by jumperson** [deepmedia/Transcoder#161]
I used the demo app to select and run one video with audio and one without audio, and I got the following error:

```
E/TranscodeEngine: Unexpected error while transcoding.
    java.lang.IllegalStateException: Of all AUDIO sources, some have a AUDIO track, some don't.
        at com.otaliastudios.transcoder.internal.Tracks.resolveTrack(Tracks.kt:80)
        at com.otaliastudios.transcoder.internal.Tracks.<init>(Tracks.kt:27)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.<init>(DefaultTranscodeEngine.kt:40)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:32)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by usmanrana-ilsa** [comment]
Facing almost similar issue with Audio. For some videos the video duration is changed (i.e. 9 secs video is converted to 15 or 18 seconds) and audio gets effected accordingly.

**Comment by VOstopolets** [comment]
Any updates?

**Comment by timcreatedit** [comment]
This issue seems related to #180. The library should technically add `BlankAudioDataSource` to every video that doesn't have it's own audio track before transcoding, however this doesn't seem to work at the moment.

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Let's track this in #180
