### ISSUE TITLE
 Unexpected error while transcoding.     android.media.MediaCodec$CodecException: Error 0xffffec77

### ISSUE THREAD

**Issue by ThuNguyenNTQ** [deepmedia/Transcoder#174]
Can anyone help me check this issue

E/TranscodeEngine: Unexpected error while transcoding.
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.otaliastudios.transcoder.internal.codec.Decoder.initialize(Decoder.kt:60)
        at com.otaliastudios.transcoder.internal.codec.Decoder.initialize(Decoder.kt:33)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.<init>(Pipeline.kt:16)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.<init>(Unknown Source:0)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline$Companion.build$lib_release(Pipeline.kt:62)
        at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt.VideoPipeline(pipelines.kt:58)
        at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt.RegularPipeline(pipelines.kt:47)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.createPipeline(DefaultTranscodeEngine.kt:82)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.access$createPipeline(DefaultTranscodeEngine.kt:27)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$segments$1.invoke(DefaultTranscodeEngine.kt:42)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$segments$1.invoke(DefaultTranscodeEngine.kt:42)
        at com.otaliastudios.transcoder.internal.Segments.tryCreateSegment(Segments.kt:87)
        at com.otaliastudios.transcoder.internal.Segments.next(Segments.kt:46)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:113)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by khemrajiitk** [comment]
I am also facing same issue multiple times?

@ThuNguyenNTQ any solution ?

**Comment by natario1** [comment]
Seems to be related to https://github.com/deepmedia/Transcoder/issues/43 (too many transcoding process, or maybe concurrency with a video player, or other encoders/decoders). If it's not the case, please attach a sample video so I can reproduce the issue.
