### ISSUE TITLE
MPEG4 movie File Encoding fails（H.264）

### ISSUE THREAD

**Issue by st-miz** [deepmedia/Transcoder#175]
Dear OSS developers.

Unexpected error while transcoding.
Detailed information is below.
I would be very happy if you could fix it.

### Android device info
・motorola moto g30
・OS Android 11

### movie file info
・mpeg4
・codec AAC、H264

### log

2022-05-16 15:06:10.736 2814-4164/hogehogeApp.debug I/ExtendedACodec: setupVideoEncoder()
2022-05-16 15:06:10.736 2814-4164/hogehogeApp.debug I/ACodec: [OMX.qcom.video.encoder.avc] setupVideoEncoder mime(video/avc) colorFormat(7f000789)
2022-05-16 15:06:10.737 2814-4164/hogehogeApp.debug W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
2022-05-16 15:06:10.737 2814-4164/hogehogeApp.debug W/OMXUtils: do not know color format 0x7fa30c00 = 2141391872
2022-05-16 15:06:10.737 2814-4164/hogehogeApp.debug W/OMXUtils: do not know color format 0x7f000789 = 2130708361
2022-05-16 15:06:10.738 2814-4164/hogehogeApp.debug I/ACodec: width height(1080x1920) stride(1080) sliceHeight(1920)
2022-05-16 15:06:10.738 2814-4164/hogehogeApp.debug E/ACodec: [OMX.qcom.video.encoder.avc] failed to set input port definition parameters.
2022-05-16 15:06:10.738 2814-4164/hogehogeApp.debug E/ExtendedACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -12
2022-05-16 15:06:10.738 2814-4164/hogehogeApp.debug E/ACodec: signalError(omxError 0x80001001, internalError -12)
2022-05-16 15:06:10.738 2814-4164/hogehogeApp.debug E/ACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -12
2022-05-16 15:06:10.738 2814-4164/hogehogeApp.debug E/ACodec: signalError(omxError 0x80001001, internalError -12)
2022-05-16 15:06:10.738 2814-4163/hogehogeApp.debug E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 3
2022-05-16 15:06:10.738 2814-4163/hogehogeApp.debug E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 0
2022-05-16 15:06:10.738 2814-4153/hogehogeApp.debug E/MediaCodec: configure failed with err 0xfffffff4, resetting...
2022-05-16 15:06:11.089 2814-4153/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd77340) release
2022-05-16 15:06:11.097 2814-4153/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd77340) init name(OMX.qcom.video.encoder.avc)
2022-05-16 15:06:11.100 2814-4164/hogehogeApp.debug I/OMXClient: IOmx service obtained
2022-05-16 15:06:11.104 2814-4163/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd77340) Component Allocated (OMX.qcom.video.encoder.avc)
2022-05-16 15:06:11.108 2814-4153/hogehogeApp.debug E/TranscodeEngine: Unexpected error while transcoding.
    android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.otaliastudios.transcoder.internal.Codecs$encoders$1$lazyVideo$2.invoke(Codecs.kt:44)
        at com.otaliastudios.transcoder.internal.Codecs$encoders$1$lazyVideo$2.invoke(Codecs.kt:41)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.otaliastudios.transcoder.internal.Codecs$encoders$1.getLazyVideo(Codecs.kt:41)
        at com.otaliastudios.transcoder.internal.Codecs$encoders$1.get(Codecs.kt:50)
        at com.otaliastudios.transcoder.internal.Codecs$encoders$1.get(Codecs.kt:30)
        at com.otaliastudios.transcoder.internal.codec.Encoder.<init>(Encoder.kt:43)
        at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt$VideoPipeline$1.invoke(pipelines.kt:64)
        at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt$VideoPipeline$1.invoke(pipelines.kt:58)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline$Companion.build$lib_release(Pipeline.kt:65)
        at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt.VideoPipeline(pipelines.kt:58)
        at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt.RegularPipeline(pipelines.kt:47)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.createPipeline(DefaultTranscodeEngine.kt:82)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.access$createPipeline(DefaultTranscodeEngine.kt:27)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$segments$1.invoke(DefaultTranscodeEngine.kt:42)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$segments$1.invoke(DefaultTranscodeEngine.kt:42)
        at com.otaliastudios.transcoder.internal.Segments.tryCreateSegment(Segments.kt:87)
        at com.otaliastudios.transcoder.internal.Segments.next(Segments.kt:46)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:113)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-05-16 15:06:11.108 2814-4153/hogehogeApp.debug I/Decoder(AUDIO,0): release(): releasing codec. dequeuedInputs=0 dequeuedOutputs=0
2022-05-16 15:06:11.109 2814-4153/hogehogeApp.debug I/MediaCodec: (0xb400007ccbba7660) stop
2022-05-16 15:06:11.110 2814-4154/hogehogeApp.debug D/CCodecBufferChannel: [c2.android.aac.decoder#329] MediaCodec discarded an unknown buffer
2022-05-16 15:06:11.110 2814-4154/hogehogeApp.debug I/chatty: uid=10298(hogehogeApp.debug) identical 2 lines
2022-05-16 15:06:11.110 2814-4154/hogehogeApp.debug D/CCodecBufferChannel: [c2.android.aac.decoder#329] MediaCodec discarded an unknown buffer
2022-05-16 15:06:11.112 2814-4153/hogehogeApp.debug I/Encoder(AUDIO,0): release(): ownsStop=true dequeuedInputs=0 dequeuedOutputs=0
2022-05-16 15:06:11.112 2814-4153/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd76330) stop
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err: android.media.MediaCodec$CodecException: Error 0xfffffff4
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:2127)
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:2043)
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Codecs$encoders$1$lazyVideo$2.invoke(Codecs.kt:44)
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Codecs$encoders$1$lazyVideo$2.invoke(Codecs.kt:41)
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
2022-05-16 15:06:11.113 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Codecs$encoders$1.getLazyVideo(Codecs.kt:41)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Codecs$encoders$1.get(Codecs.kt:50)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Codecs$encoders$1.get(Codecs.kt:30)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.codec.Encoder.<init>(Encoder.kt:43)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt$VideoPipeline$1.invoke(pipelines.kt:64)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt$VideoPipeline$1.invoke(pipelines.kt:58)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.pipeline.Pipeline$Companion.build$lib_release(Pipeline.kt:65)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt.VideoPipeline(pipelines.kt:58)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.pipeline.PipelinesKt.RegularPipeline(pipelines.kt:47)
2022-05-16 15:06:11.114 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.createPipeline(DefaultTranscodeEngine.kt:82)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.access$createPipeline(DefaultTranscodeEngine.kt:27)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$segments$1.invoke(DefaultTranscodeEngine.kt:42)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$segments$1.invoke(DefaultTranscodeEngine.kt:42)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Segments.tryCreateSegment(Segments.kt:87)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.Segments.next(Segments.kt:46)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:113)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-05-16 15:06:11.115 2814-2814/hogehogeApp.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-05-16 15:06:11.116 2814-2814/hogehogeApp.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-05-16 15:06:11.116 2814-2814/hogehogeApp.debug W/System.err:     at java.lang.Thread.run(Thread.java:923)
2022-05-16 15:06:11.116 2814-4156/hogehogeApp.debug D/CCodecBufferChannel: [c2.android.aac.encoder#560] MediaCodec discarded an unknown buffer
2022-05-16 15:06:11.116 2814-4156/hogehogeApp.debug I/chatty: uid=10298(hogehogeApp.debug) MediaCodec_loop identical 3 lines
2022-05-16 15:06:11.116 2814-4156/hogehogeApp.debug D/CCodecBufferChannel: [c2.android.aac.encoder#560] MediaCodec discarded an unknown buffer
2022-05-16 15:06:11.118 2814-4153/hogehogeApp.debug I/DefaultDataSource(2): releaseTrack(AUDIO)
2022-05-16 15:06:11.122 2814-4153/hogehogeApp.debug D/MPEG4Writer: reset()
2022-05-16 15:06:11.122 2814-4153/hogehogeApp.debug D/MPEG4Writer: release()
2022-05-16 15:06:11.122 2814-4153/hogehogeApp.debug D/MPEG4Writer: ftruncate mPreAllocateFileEndOffset:0 mOffset:0 mMdatEndOffset:0 diff:0
2022-05-16 15:06:11.122 2814-4154/hogehogeApp.debug I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2022-05-16 15:06:11.132 2814-4153/hogehogeApp.debug I/DataSources: release(): releasing...
2022-05-16 15:06:11.132 2814-4153/hogehogeApp.debug I/DataSources: deinitializing hogehogeApp.controller.videoedit.SafelyClipDataSource@ee75d81... (isInit=true)
2022-05-16 15:06:11.133 2814-4153/hogehogeApp.debug I/DefaultDataSource(2): deinitialize(): deinitializing...
2022-05-16 15:06:11.135 2814-4153/hogehogeApp.debug I/DataSources: deinitializing hogehogeApp.controller.videoedit.SafelyClipDataSource@ee75d81... (isInit=false)
2022-05-16 15:06:11.135 2814-4153/hogehogeApp.debug I/DataSources: release(): released.
2022-05-16 15:06:11.139 2814-4153/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd7b380) init name(OMX.qcom.video.encoder.avc)
2022-05-16 15:06:11.143 2814-4174/hogehogeApp.debug I/OMXClient: IOmx service obtained
2022-05-16 15:06:11.147 2814-4173/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd7b380) Component Allocated (OMX.qcom.video.encoder.avc)
2022-05-16 15:06:11.150 2814-4153/hogehogeApp.debug I/MediaCodec: (0xb400007ccbd7b380) configure surface(0x0) crypto(0x0) flags(1)
2022-05-16 15:06:11.150 2814-4153/hogehogeApp.debug D/MediaCodec: (0xb400007ccbd7b380) configure format: AMessage(what = 0x00000000) = {

**Comment by hust-twj** [comment]
same issue

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Hi, it's hard to tell what's wrong. If you still have this issue, please provide a sample video so I can reproduce on my device. Thanks!
