### ISSUE TITLE
IllegalArgumentException: bufferInfo must specify a valid buffer offset, size and presentation time

### ISSUE THREAD

**Issue by MeiLaoban** [deepmedia/Transcoder#197]
The problem with android 10 is that there are always errors when the video is nearly compressed.

java.lang.IllegalArgumentException: bufferInfo must specify a valid buffer offset, size and presentation time
                                                                                                     at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:682)
                                                                                                     at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:163)
                                                                                                     at com.otaliastudios.transcoder.internal.utils.EosIgnoringDataSink.writeTrack(eos.kt:28)
                                                                                                     at com.otaliastudios.transcoder.internal.data.Writer.step(Writer.kt:50)
                                                                                                     at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
                                                                                                     at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
                                                                                                     at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
                                                                                                     at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
                                                                                                     at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
                                                                                                     at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
                                                                                                     at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
                                                                                                     at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
                                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                     at java.lang.Thread.run(Thread.java:919)

**Comment by natario1** [comment]
Can you provide a sample video and the code that you use to replicate the error?
