### ISSUE TITLE
Exception on mkv transcoding on Vivo Y81i Android 8.1

### ISSUE THREAD

**Issue by nzackoya** [deepmedia/Transcoder#59]
java.nio.BufferOverflowException
        at java.nio.ByteBuffer.put(ByteBuffer.java:544)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.enqueue(DefaultDataSink.java:156)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:136)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:369)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
VideosKt$cutVideoTo15Seconds: java.nio.BufferOverflowException
        at java.nio.ByteBuffer.put(ByteBuffer.java:544)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.enqueue(DefaultDataSink.java:156)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:136)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:369)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jumperson** [comment]
May be fix this issue by #166.

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

I'm going to close this since it's so old. If it's still an issue please provide a sample file so I can investigate.
