### ISSUE TITLE
writeSampleData returned an error

### ISSUE THREAD

**Issue by DemoSourceCodes** [deepmedia/Transcoder#98]
I am not able to merge video and audio, while doing so I got this error in the mid of the process.

 W/DefaultDataSink: Failed to release the muxer.
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:245)
        at android.media.MediaMuxer.release(MediaMuxer.java:485)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.release(DefaultDataSink.java:206)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:394)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

E/Transcoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:473)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:151)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:373)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by zaheerahmad** [comment]
Hi Is there any updates on this issue? I am facing the same issue on few devices.
- Mi
- OnePlus
- Nokia

Its working fine on Samsung & some devices on Huawei.

**Comment by natario1** [comment]
(Pasted to all my answers today: it's been a long time since my last issues review. I am sorry about the delay and I know you likely have moved on by now. Still, I'm going to answer where I can)

Hi, this is too vague to be actionable. If you have problems with a specific video file please attach it and I'll take a look. Unfortunately MediaMuxer returns crappy error messages.
